### PR TITLE
TBS-4157: RDF-Delta 1.0.2-tq-2

### PR DESCRIPTION
**Pull request by bvosburgh-tq**
Changes:
* Bump the Maven version to 1.0.2-tq-1
* Implement DeltaConnection.close() to gracefully clean up threads.

This is more of a "review request", as the changes will not be merged into 'main'.

### CODE REVIEW

**Comment by bvosburgh-tq** [comment]
Sorry, again. Wrong repository. Again. My bad. : (

But these changes do point to a couple of problems we are having with rdf-delta: There is no way to clean up the threads started by `DeltaConnection` and `LogLockMgr`.

**Comment by afs** [comment]
You can change the repo remote with `git remote set-url origin new.git.url/here` or edit the `.git/config` file.

To everyone: TopQuadrant does not use the the full RDF Delta client so situations they encounter may not apply to released RDF Delta + Fuseki.
---
Why and how are you closing connections?

Please could you make a PR against the RDF Delta repo that contains only changes about threads.

**Comment by bvosburgh-tq** [comment]
> You can change the repo remote with `git remote set-url origin new.git.url/here` or edit the `.git/config` file.
The problem is not the destination of `git push` commands, it is the default "base repository" set by GitHub when I open a Pull Request. If I forget to change the "base repository" from `afs/rdf-delta` to `TopQuadrant\rdf-delta` (which is a setting that I never need to change in a typical PR), the PR is generated against `afs/rdf-delta`. And there is no easy way to change that default setting. : (

> 
> To everyone watching -- TopQuadrant does not use the the full RDF Delta client so situations they encounter may not apply to released RDF Delta + Fuseki.
I am still figuring out how we (TopQuadrant) use the RDF Delta client. Since you seem to have done much of the work earlier, can you point out how I might improve our usage? I have not found any documentation describing how a typical client should use the client library. Did I miss something?

> Why and how are you closing connections?
Why: When our app is running as a Tomcat war and it uses the RDF Delta client, the JVM running Tomcat is unable to shutdown completely because there are a number of RDF Delta threads still running; at least 1, and potentially 2, threads per `DeltaConnection`.

How: During our app shutdown, we loop through the existing RDF Delta connections and call `DeltaConnection.close()`, which, with the changes in this PR, will gracefully shut down the thread(s) the connection had previously spawned.

> Please could you make a PR against the RDF Delta repo that contains only changes about threads.
Will do.

Thanks!

**Comment by afs** [comment]
> the default "base repository" set by GitHub

https://stackoverflow.com/a/45550463/757100 then add `afs/rdf-delta` as another remote if you want.

> Since you seem to have done much of the work earlier, can you point out how I might improve our usage?

Both here and on users@jena, TQ reports already require some knowledge of the TQ system (from memory - I don't have a copy of the code, obviously).

Advice on closed source, proprietary software is a step too far.

> app shutdown

The threads could changed to daemon threads which don't block JVM exit.

The system has to survive abrupt termination anyway so trust that!

**Pull request closed without merging**
